version: '3.7'
services:
  hub:
    image: selenium/hub:3.141
    container_name: selenium-hub
    ports:
      - 4444:4444
    networks:
      - docker-selenium-net

  node-chrome-debug:
    image: selenium/node-chrome-debug:3.141
    container_name: node-chrome-debug
    ports:
      - 5555:5555
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    networks:
      - docker-selenium-net

  node-firefox-debug:
    image: selenium/node-firefox-debug:3.141
    container_name: node-firefox-debug
    ports:
      - 5900:5900
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    networks:
      - docker-selenium-net

networks:
  docker-selenium-net: