module.exports = {
  chrome: {
    browserName: 'Chrome',
    browser_version: 'latest',
    os: 'Windows',
    os_version: '10',
    resolution: '1280x1024',
  },
  chromeMac: {
    browserName: 'Chrome',
    browser_version: 'latest',
    os: 'OS X',
    os_version: 'Big Sur',
    resolution: '1280x1024',
  },
  firefox: {
    browserName: 'Firefox',
    browser_version: 'latest',
    os: 'Windows',
    os_version: '10',
    resolution: '1280x1024',
  },
  firefoxMac: {
    browserName: 'Firefox',
    browser_version: 'latest',
    os: 'OS X',
    os_version: 'Big Sur',
    resolution: '1280x1024',
  },
  firefoxMac80: {
    browserName: 'Firefox',
    browser_version: 80,
    os: 'OS X',
    os_version: 'Big Sur',
    resolution: '1280x1024',
  },
  ie: {
    browserName: 'IE',
    os: 'Windows',
    os_version: '10',
    resolution: '1280x1024',
  },
  ie10: {
    browserName: 'IE',
    browser_version: '10.0',
    os: 'Windows',
    os_version: '8',
    resolution: '1280x1024',
  },
  edge: {
    browserName: 'Edge',
    browser_version: '15.0',
    os: 'Windows',
    os_version: '10',
    resolution: '1280x1024',
  },
  safari: {
    browserName: 'Safari',
    os: 'OS X',
    os_version: 'Sierra',
    resolution: '1280x1024',
  },
  safari9: {
    browserName: 'Safari',
    browser_version: '9.1',
    os: 'OS X',
    os_version: 'El Capitan',
    resolution: '1280x1024',
  },
};
